name: continuous integration

on:
  push: 
    branches:
      - main
  workflow_dispatch:
    
env: 
  DOTNET_VERSION: '6.0.x'
  PUBLISH_PATH: '.'
  
jobs:
  build: 
    runs-on: windows-latest

    defaults:
      run: 
        working-directory: asp-dotnet-core

    steps:
      - name: checkout out code
        uses: actions/checkout@main

      - name: set up dotnet 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION}}
      
      - name: set up dependency caching for faster build
        uses: action/cache@v3
        with: 
          path: ~/.nuget/packages
          key:  ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.jason') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: build app
        run: dotnet build -c Release --no-restore


      - name: dotnet publish
        run: dotnet publish -c Release -o ${{ env.PUBLISH_PATH }}

      - name: upload artifact 
        uses: actions/upload-artifact@main
        with: 
          name: .net-app
          path: ${{ env.PUBLISH_PATH }}